// Shared audit-log model for both apps (Legion + D&D). The log rides
// along inside each app's synced board state, so it persists locally and
// is shared over the multiplayer room for free. Entries are generated by
// diffing the previous board against the new one, so any mutation is
// captured without instrumenting each call site.

export type LogActor = { name: string; color: string };

export type LogKind = "move" | "add" | "remove" | "hp" | "round" | "turn" | "vp" | "dice" | "misc";

export type LogEntry = {
  id: string;
  ts: number;
  actor: LogActor;
  kind: LogKind;
  text: string;
  /** Present on "move" entries so the ghost replay can highlight it.
   * Coordinates are in each app's native board units. */
  move?: { from: { x: number; y: number }; to: { x: number; y: number }; size?: number; color?: string };
};

export const LOG_CAP = 120;

let lc = 0;
export function logId(): string {
  lc = (lc + 1) % 100000;
  return `l_${Math.random().toString(36).slice(2, 7)}${lc}`;
}

// Append entries (already actor-stamped) to a log, keeping the newest
// LOG_CAP. Returns a new array; never mutates the input.
export function appendLog(log: LogEntry[] | undefined, entries: LogEntry[]): LogEntry[] {
  if (entries.length === 0) return log ?? [];
  const next = [...(log ?? []), ...entries];
  return next.length > LOG_CAP ? next.slice(next.length - LOG_CAP) : next;
}

// A stable actor for solo play (no room identity).
export const SOLO_ACTOR: LogActor = { name: "You", color: "#8b94a8" };

export function relativeTime(ts: number, now: number): string {
  const s = Math.max(0, Math.floor((now - ts) / 1000));
  if (s < 5) return "just now";
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  return `${h}h ago`;
}
