"""Hand-curated mercenary catalog seed.

This file is the authoritative MERCENARY_SEED, used by catalog.ts.

Generated from a deliberate vision pass over the mercenary unit cards to fix
two issues with the prior auto-generated seed:

1. Some "mercenary" units are actually Rebel-faction units that carry the
   Mercenary keyword (Wicket, Logray, Ewok Skirmishers, Ewok Slingers). They
   should appear in the Rebel unit list (primary) AND in the mercenary list
   (via also_factions).
2. Many true mercenary units (Boba Fett, Bossk, Cad Bane, IG-11 etc.) can be
   fielded by any faction army that allows mercenaries. They get
   also_factions covering the other four factions.

Costs come from the top-right corner of each card; ranks are best-effort
based on Legion army composition rules. Stats other than cost remain
placeholders for a follow-up pass.

Run: python3 scripts/build_mercenary_seed.py > /tmp/seed.ts
Then append the printed TS to catalog.seed.ts (replacing the existing
MERCENARY_SEED block).
"""
from __future__ import annotations
import sys

# (id_suffix, display_name, sub_title, points, rank, primary_faction,
#  also_factions, is_unique)
ENTRIES: list[tuple[str, str, str, int, str, str, list[str], bool]] = [
    # ---- Ewoks: primary Rebels (Bright Tree Village), Mercenary-tagged ----
    ("wicket", "Wicket", "Hero of Bright Tree", 70, "operative",
     "rebels", ["mercenary"], True),
    ("logray", "Logray", "Superstitious Shaman", 50, "support",
     "rebels", ["mercenary"], True),
    ("ewok-skirmishers", "Ewok Skirmishers", "", 40, "corps",
     "rebels", ["mercenary"], False),
    ("ewok-slingers", "Ewok Slingers", "", 40, "special-forces",
     "rebels", ["mercenary"], False),

    # ---- Pure Mercenary: Shadow Collective faction (locked to that BF) ----
    ("maul-rival", "Maul", "A Rival", 150, "commander",
     "mercenary", [], True),
    ("black-sun-vigo", "Black Sun Vigo", "", 80, "commander",
     "mercenary", [], True),
    ("gar-saxon", "Gar Saxon", "", 110, "operative",
     "mercenary", [], True),
    ("pyke-syndicate-capo", "Pyke Syndicate Capo", "", 60, "commander",
     "mercenary", [], True),
    ("black-sun-enforcers", "Black Sun Enforcers", "", 50, "corps",
     "mercenary", [], False),
    ("pyke-syndicate-foot-soldiers", "Pyke Syndicate Foot Soldiers", "",
     45, "corps", "mercenary", [], False),
    ("mandalorian-super-commandos", "Mandalorian Super Commandos", "",
     70, "special-forces", "mercenary", [], False),
    ("a-a5-speeder-truck", "A-A5 Speeder Truck", "", 95, "heavy",
     "mercenary", [], False),

    # ---- Mercenary heroes usable across factions ----
    ("boba-fett-daimyo", "Boba Fett", "Daimyo of Mos Espa", 120, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("boba-fett-bounty-hunter", "Boba Fett", "Infamous Bounty Hunter", 130,
     "operative", "mercenary",
     ["rebels", "imperials", "republic", "separatists"], True),
    ("bossk", "Bossk", "Trandoshan Terror", 105, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("cad-bane", "Cad Bane", "Galaxy's Most Wanted", 105, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("ig-11", "IG-11", "Nurse Droid", 105, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("ig-88", "IG-88", "Assassin Droid", 110, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("din-djarin", "Din Djarin", "The Mandalorian", 95, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("grogu", "Grogu", "The Child", 30, "operative",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),

    # ---- The Bad Batch (Mercenary) ----
    ("omega", "Omega", "", 50, "corps",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], True),
    ("the-bad-batch", "The Bad Batch", "", 90, "special-forces",
     "mercenary", ["rebels", "imperials", "republic", "separatists"], False),

    # ---- Generic Mercenary support / cavalry ----
    ("swoop-bike-riders", "Swoop Bike Riders", "", 80, "support",
     "mercenary", [], False),  # locked to Shadow Collective / Ohnaka
]


def main() -> int:
    print("// AUTO-GENERATED by scripts/build_mercenary_seed.py.")
    print("// Costs verified from card art top-right cost badge.")
    print("// Stats other than cost are placeholders; adjust by hand.")
    print("export const MERCENARY_SEED: Unit[] = [")
    for (slug, name, sub, pts, rank, faction, also, uniq) in ENTRIES:
        also_str = ", ".join(f'"{f}"' for f in also)
        also_part = f"    also_factions: [{also_str}],\n" if also else ""
        sub_part = f'    sub_title: "{sub}",\n' if sub else ""
        unique_str = "true" if uniq else "false"
        print("  {")
        print(f'    id: "mercenary-{slug}",')
        print(f'    name: "{name}",')
        sys.stdout.write(sub_part)
        print(f"    is_unique: {unique_str},")
        print(f'    faction: "{faction}",')
        sys.stdout.write(also_part)
        print(f'    type: "trooper",')
        print(f"    points: {pts},")
        print(f'    rank: "{rank}",')
        print("    miniatures: 1,")
        print("    wounds: 1,")
        print('    defense: "white",')
        print("    has_defense_surge: false,")
        print("  },")
    print("];")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
